"""Audit-key generation helpers.

Generates Ed25519 keypairs used for signing audit-log entries.
PQC keys (ML-DSA-65) are generated by :mod:`forensics.quantum.keygen`.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def generate_ed25519(out_dir: Path) -> tuple[Path, Path]:
    """Generate a fresh Ed25519 keypair under *out_dir*.

    Returns ``(private_path, public_path)``. Files are written with
    ``0600`` (private) and ``0644`` (public) and never overwrite an
    existing key.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    priv_path = out_dir / "audit_ed25519.key"
    pub_path  = out_dir / "audit_ed25519.pub"

    if priv_path.exists():
        return priv_path, pub_path  # idempotent

    priv = Ed25519PrivateKey.generate()

    # Private key — write atomically with restrictive perms before any data.
    priv_bytes = priv.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    fd = os.open(priv_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, priv_bytes)
    finally:
        os.close(fd)

    pub_bytes = priv.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    pub_path.write_bytes(pub_bytes)
    pub_path.chmod(0o644)

    return priv_path, pub_path


def _cli(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="forensics-audit-keygen",
        description="Generate audit-signing keypairs.",
    )
    sub = p.add_subparsers(dest="alg", required=True)

    e = sub.add_parser("ed25519", help="Generate Ed25519 keypair.")
    e.add_argument("--out-dir", required=True, type=Path,
                   help="Directory to write the keypair into.")

    args = p.parse_args(argv)
    if args.alg == "ed25519":
        priv, pub = generate_ed25519(args.out_dir)
        print(f"private: {priv}")
        print(f"public:  {pub}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
