#!/bin/bash
# ==============================================================================
# CRYPTOGRAPHIC KEYS INITIALIZATION
# Initializes Ed25519 and GPG keys for audit system
# ==============================================================================

set -e

KEYS_DIR="/keys"
mkdir -p "$KEYS_DIR"

echo "🔐 Initializing cryptographic keys for audit system..."

# Keys will be generated by Python audit-logger on first run
# This script ensures directory exists and has correct permissions

chmod 700 "$KEYS_DIR"

echo "✅ Keys directory initialized: $KEYS_DIR"
